#!/usr/bin/env python3
# Name: Your full name (cruzID)
# Group Members: List full names (and cruzIDs) or “None”

class ProteinParam :
# These tables are for calculating:
#     molecular weight (aa2mw), along with the mol. weight of H2O (mwH2O)
#     absorbance at 280 nm (aa2abs280)
#     pKa of positively charged Amino Acids (aa2chargePos)
#     pKa of negatively charged Amino acids (aa2chargeNeg)
#     and the constants aaNterm and aaCterm for pKa of the respective termini
#  Feel free to move these to appropriate methods as you like

# As written, these are accessed as class attributes, for example:
# ProteinParam.aa2mw['A'] or ProteinParam.mwH2O

    aa2mw = {
        'A': 89.093,  'G': 75.067,  'M': 149.211, 'S': 105.093, 'C': 121.158,
        'H': 155.155, 'N': 132.118, 'T': 119.119, 'D': 133.103, 'I': 131.173,
        'P': 115.131, 'V': 117.146, 'E': 147.129, 'K': 146.188, 'Q': 146.145,
        'W': 204.225,  'F': 165.189, 'L': 131.173, 'R': 174.201, 'Y': 181.189
        }
    
    def __init__ (self, protein):
        self.protein = protein.upper()
        self.count = {}
        for key,value in self.aa2mw.items():
            self.count[key] = protein.count(key)

    def aaCount (self):
        value = self.count.values()
        return sum(value)
    
    def pIm(self, mid = 700, add = 350):
        if (abs(self._charge_(0)) < abs(self._charge_(0.01))):
            return 0
        elif (abs(self._charge_(14)) < abs(self._charge_(13.99))):
            return 14
        elif (abs(self._charge_(mid/100.0)) > abs(self._charge_((mid + 1) / 100.0))):
            return self.pI((int)(mid+add),(int)(add/2))
        elif (abs(self._charge_(mid/100.0)) > abs(self._charge_((mid - 1) / 100.0))):
            return self.pI((int)(mid - add),(int)(add / 2))
        else:
            return (mid / 100)

    def pI (self):
        ph = 0.01
        charge = self._charge_(0)
        while ph <= 14:
            if abs(self._charge_(ph)) > abs(charge):
                return ph - 0.01
            charge = self._charge_(ph)
            ph += 0.01
        return 14

    def aaComposition (self) :
        return self.count

    def _charge_ (self, ph):
        aaNterm = 9.69
        aaCterm = 2.34
        aa2chargePos = {'K': 10.5, 'R':12.4, 'H':6}
        aa2chargeNeg = {'D': 3.86, 'E': 4.25, 'C': 8.33, 'Y': 10}
        first = 0
        for key, value in aa2chargePos.items():
            first += self.count[key]*(10**aa2chargePos[key] / (10**aa2chargePos[key]+10**ph))
        first += (10**aaNterm / (10**aaNterm + 10**ph))
        second = 0
        for key,value in aa2chargeNeg.items():
            second += self.count[key]*(10**ph / (10**aa2chargeNeg[key] + 10**ph))
        second += (10**ph / (10**aaCterm + 10**ph))
        return first - second

    def molarExtinction (self):
        aa2abs280= {'Y':1490, 'W': 5500, 'C': 125}
        mol = 0 
        for key, value in aa2abs280.items():
            mol += self.count[key]*aa2abs280[key]
        return mol

    def massExtinction (self):
        myMW =  self.molecularWeight()
        return self.molarExtinction() / myMW if myMW else 0.0

    def molecularWeight (self):
        mwH2O = 18.015
        sum = self.mwH2O
        for key,value in self.aa2mw.items():
            sum += self.aa2mw[key] * self.count[key] - self.mwH2O * self.count[key]
        return sum


# Please do not modify any of the following.  This will produce a standard output that can be parsed
    
import sys
def main():
    inString = input('protein sequence?')
    while inString:
        myParamMaker = ProteinParam(inString)
        myAAnumber = myParamMaker.aaCount()
        print ("Number of Amino Acids: {aaNum}".format(aaNum = myAAnumber))
        print ("Molecular Weight: {:.1f}".format(myParamMaker.molecularWeight()))
        print ("molar Extinction coefficient: {:.2f}".format(myParamMaker.molarExtinction()))
        print ("mass Extinction coefficient: {:.2f}".format(myParamMaker.massExtinction()))
        print ("Theoretical pI: {:.2f}".format(myParamMaker.pI()))
        print ("Amino acid composition:")
        
        if myAAnumber == 0 : myAAnumber = 1  # handles the case where no AA are present 
        
        for aa,n in sorted(myParamMaker.aaComposition().items(), 
                           key= lambda item:item[0]):
            print ("\t{} = {:.2%}".format(aa, n/myAAnumber))
        inString = input('protein sequence?')

if __name__ == "__main__":
    main()