#!/usr/bin/env python3 
# Name: Your full name  
# Group Members: List full names or “None”

'''
Read a DNA string from user input and return a collapsed substring of embedded Ns to: {count}.

Example: 
 input: AaNNNNNNGTC
output: AA{6}GTC

Any lower case letters are converted to uppercase
'''
#Function to count length of DNA
class DNAstring (str):
  def length (self):
    return (length(self))

    # Function to clean DNA 
  def purify(self):
        
        return pureDNA
   
#Function that is called   
def main():
  ''' Get user DNA data and clean it up.'''
  while (True):
    data = input('DNA data?')
    thisDNA = DNAstring (data)
    pureData = thisDNA.purify()
    print (pureData)
    
main()